export const DEFAULT_DONATION_CATEGORIES = [
  {
    id: 'game-debuffs',
    name: 'Ігрові дебафи',
    donations: [
      {
        id: 'random-debuff',
        name: 'Випадковий ігровий дебаф',
        description: 'Один випадковий дебаф з усіх ігрових нагород',
        price: 150,
        currency: 'UAH',
        durationMinutes: 10,
        hasTimer: true,
        isRandom: true,
        randomPoolCategory: 'game-debuffs',
      },
      {
        id: 'disable-map-hints',
        name: 'Вимкнути карту та підказки',
        price: 100,
        currency: 'UAH',
        durationMinutes: 10,
        hasTimer: true,
      },
      {
        id: 'no-healing',
        name: 'Заборонено лікування',
        price: 100,
        currency: 'UAH',
        durationMinutes: 10,
        hasTimer: true,
      },
      {
        id: 'invert-controls',
        name: 'Інвертоване керування',
        price: 200,
        currency: 'UAH',
        durationMinutes: 10,
        hasTimer: true,
      },
      {
        id: 'starter-weapon-only',
        name: 'Лише стартова зброя',
        price: 200,
        currency: 'UAH',
        durationMinutes: 10,
        hasTimer: true,
      },
      {
        id: 'no-running',
        name: 'Заборона бігу',
        price: 200,
        currency: 'UAH',
        durationMinutes: 10,
        hasTimer: true,
      },
      {
        id: 'no-dodge-block-roll',
        name: 'Без ухилень, блоків та перекатів',
        price: 200,
        currency: 'UAH',
        durationMinutes: 10,
        hasTimer: true,
      },
      {
        id: 'blind-play',
        name: 'Вимкнути монітор і грати всліпу (лише підказки з чату)',
        price: 300,
        currency: 'UAH',
        durationMinutes: 5,
        hasTimer: true,
      },
    ],
  },
  {
    id: 'music',
    name: 'Музика',
    donations: [
      {
        id: 'song-request',
        name: 'Замовити будь-яку пісню (повне прослуховування на стрімі)',
        price: 200,
        currency: 'UAH',
        durationMinutes: null,
        hasTimer: false,
      },
      {
        id: 'guitar-streamer-choice',
        name: 'Виступ на гітарі (на вибір стрімера)',
        price: 500,
        currency: 'UAH',
        durationMinutes: null,
        hasTimer: false,
      },
      {
        id: 'guitar-donor-choice',
        name: 'Виступ на гітарі (ваш вибір)',
        price: 1000,
        currency: 'UAH',
        durationMinutes: null,
        hasTimer: false,
      },
    ],
  },
  {
    id: 'interaction',
    name: 'Взаємодія',
    donations: [
      {
        id: 'watch-video-together',
        name: 'Переглянути ваше відео разом на стрімі (до 10 хв)',
        price: 200,
        currency: 'UAH',
        durationMinutes: 10,
        hasTimer: true,
      },
      {
        id: 'english-only',
        name: 'Режим лише англійською',
        price: 500,
        currency: 'UAH',
        durationMinutes: 15,
        hasTimer: true,
      },
      {
        id: 'discord-with-donor',
        name: '10 хвилин у Discord з донатером',
        price: 500,
        currency: 'UAH',
        durationMinutes: 10,
        hasTimer: true,
      },
      {
        id: 'unfiltered-dev-story',
        name: 'Нецензурна історія про Rage of Mechs / інший dev-проєкт',
        price: 500,
        currency: 'UAH',
        durationMinutes: null,
        hasTimer: false,
      },
      {
        id: 'watch-anime',
        name: 'Переглянути 3 серії аніме на ваш вибір',
        price: 1000,
        currency: 'UAH',
        durationMinutes: null,
        hasTimer: false,
      },
      {
        id: 'live-script-writing',
        name: 'Написати сценарій відео в прямому ефірі',
        price: 1000,
        currency: 'UAH',
        durationMinutes: null,
        hasTimer: false,
      },
    ],
  },
  {
    id: 'major-requests',
    name: 'Великі запити',
    donations: [
      {
        id: 'request-next-game',
        name: 'Замовити будь-яку гру на наступний стрім',
        price: 1000,
        currency: 'UAH',
        durationMinutes: null,
        hasTimer: false,
      },
      {
        id: 'change-game-now',
        name: 'Негайно змінити поточну гру',
        price: 1000,
        currency: 'UAH',
        durationMinutes: null,
        hasTimer: false,
      },
      {
        id: 'restart-game-hard',
        name: 'Перезапустити гру з початку на найвищій складності',
        price: 1000,
        currency: 'UAH',
        durationMinutes: null,
        hasTimer: false,
      },
      {
        id: 'hogwarts-marathon',
        name: 'Кинути все і грати Hogwarts Legacy 3 години',
        price: 3000,
        currency: 'UAH',
        durationMinutes: 180,
        hasTimer: true,
      },
      {
        id: 'chat-game-jam',
        name: 'CHAT GAME JAM — жива сесія розробки гри',
        price: 5000,
        currency: 'UAH',
        durationMinutes: null,
        hasTimer: false,
      },
    ],
  },
];

export const DONATION_CATEGORIES = DEFAULT_DONATION_CATEGORIES;
